# Docker Compose configuration for ESP32-C6 development
# Provides ESP-IDF v5.3 development environment

version: '3.8'

services:
  esp-idf:
    image: espressif/idf:v5.3
    container_name: v4-ports-esp-idf
    volumes:
      # Mount project directory
      - .:/project
      # Mount V4 (required for HAL headers)
      - ../V4:/v4:ro
      # Mount V4-front (required for REPL example)
      - ../V4-front:/v4-front:ro
      # Mount SSH keys for git operations (optional)
      - ~/.ssh:/root/.ssh:ro
      # Persistent build cache
      - esp-idf-cache:/root/.espressif
    environment:
      # Set V4 path for build system
      - V4_PATH=/v4
    working_dir: /project
    command: /bin/bash
    tty: true
    stdin_open: true
    # Device access for flashing (optional, uncomment if needed)
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
    privileged: false
    network_mode: bridge

volumes:
  # Named volume for ESP-IDF cache
  esp-idf-cache:
