name: ESP32-C6 Build CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-esp32c6:
    name: Build ESP32-C6 Examples
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.3

    steps:
      - name: Checkout V4-ports
        uses: actions/checkout@v4
        with:
          path: v4-ports

      - name: Checkout V4
        uses: actions/checkout@v4
        with:
          repository: kirisaki/v4
          path: v4
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout V4-front
        uses: actions/checkout@v4
        with:
          repository: kirisaki/V4-front
          path: v4-front
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout V4-repl
        uses: actions/checkout@v4
        with:
          repository: kirisaki/V4-repl
          path: v4-repl
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout V4-hal
        uses: actions/checkout@v4
        with:
          repository: kirisaki/V4-hal
          path: v4-hal
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment
        run: |
          . $IDF_PATH/export.sh
          echo "ESP-IDF version:"
          idf.py --version

      - name: Build v4-blink
        working-directory: v4-ports/esp32c6/examples/v4-blink
        run: |
          . $IDF_PATH/export.sh
          export V4_PATH=$GITHUB_WORKSPACE/v4
          export V4_FRONT_PATH=$GITHUB_WORKSPACE/v4-front
          export V4_REPL_PATH=$GITHUB_WORKSPACE/v4-repl
          export V4_HAL_PATH=$GITHUB_WORKSPACE/v4-hal
          echo "V4_PATH is set to: $V4_PATH"
          echo "V4_FRONT_PATH is set to: $V4_FRONT_PATH"
          echo "V4_REPL_PATH is set to: $V4_REPL_PATH"
          echo "V4_HAL_PATH is set to: $V4_HAL_PATH"
          ls -la $V4_PATH/include/v4/ || echo "V4 headers not found"
          idf.py build

      # v4-repl-demo requires v4 and v4-front
      # Uncomment when dependencies are available
      # - name: Build v4-repl-demo
      #   working-directory: v4-ports/esp32c6/examples/v4-repl-demo
      #   run: |
      #     . $IDF_PATH/export.sh
      #     export V4_PATH=$GITHUB_WORKSPACE/v4
      #     export V4_FRONT_PATH=$GITHUB_WORKSPACE/v4-front
      #     idf.py build

      - name: Upload v4-blink artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v4-blink-esp32c6
          path: |
            v4-ports/esp32c6/examples/v4-blink/build/*.bin
            v4-ports/esp32c6/examples/v4-blink/build/*.elf
          retention-days: 7

      # - name: Upload v4-repl-demo artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: v4-repl-demo-esp32c6
      #     path: |
      #       v4-ports/esp32c6/examples/v4-repl-demo/build/*.bin
      #       v4-ports/esp32c6/examples/v4-repl-demo/build/*.elf
      #     retention-days: 7

  formatting:
    name: Code Formatting Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check C/C++ formatting
        run: |
          find esp32c6 -type f \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' \) \
            -not -path "*/build/*" | \
            xargs clang-format --dry-run --Werror || \
            (echo "❌ C/C++ formatting check failed. Run 'make format' to fix." && exit 1)

      - name: Install cmake-format
        run: pip install cmake-format pyyaml

      - name: Check CMake formatting
        run: |
          find esp32c6 -name 'CMakeLists.txt' -o -name '*.cmake' | \
            xargs cmake-format --check || \
            (echo "❌ CMake formatting check failed. Run 'make format' to fix." && exit 1)
